version: '3.7'

services:
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_USER=${MONGO_USER:-user}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-password}
      - MONGO_DATABASE=${MONGO_DATABASE:-pie-cloud-db}
      - MONGO_TEST_DATABASE=${MONGO_TEST_DATABASE:-pie-cloud-test-db}
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"

  pie-cloud:
    image: 'pie-cloud:latest'
    container_name: pie-cloud
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USER:-user}:${MONGO_PASSWORD:-password}@mongodb:27017/${MONGO_DATABASE:-pie-cloud-db}
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
    depends_on:
      - kafka
      - mongodb

volumes:
  mongodb_data:
    driver: local